### ISSUE TITLE
Unusable. 

### ISSUE THREAD

**Issue by dflantz** [yanniskatsaros/who-scraped-my-car#1]
I downloaded this tool after some jerk keyed "$TSLA 7/17 2000c" into my PT Cruiser's ceramic, diarrhea-colored coating. The cops said there was nothing they could do, and that I should "YOLO my mortgage on FDs," whatever that means.

Anyway, I found this tool and couldn't wait to get a GPS track on the perp. Instead, it kept telling me to install "cobra" or something, and when I finally got that figured out, it started vomiting out a bunch of Auto Trader links. 

2/10, pls refund.

**Comment by yanniskatsaros** [comment]
- [x] Find diarrhea-colored, ceramic coating PT Cruiser on AutoTrader

I think I [found your car](https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=554968646&zip=78254&referrer=%2Fcars-for-sale%2Fsearchresults.xhtml%3Fzip%3D78254%26extColorsSimple%3DBEIGE%252CBROWN%26sortBy%3Drelevance%26incremental%3Dall%26firstRecord%3D0%26marketExtension%3Dinclude%26modelCodeList%3DPTCRUIS%26makeCodeList%3DCHRY%26searchRadius%3D0%26isNewSearch%3Dfalse&numRecords=25&firstRecord=0&modelCodeList=PTCRUIS&makeCodeList=CHRY&searchRadius=0&makeCode1=CHRY&modelCode1=PTCRUIS&clickType=listing) bro! Best of luck on your 4/20 $TSLA mortgage

![image](https://user-images.githubusercontent.com/32942328/88507433-05f7d100-cfa2-11ea-89ed-8179527edfd0.png)
